# 🎨 Theme Configuration
# Beautiful themes for the GitHub Repository Analyzer

themes:
  # Light Theme - Clean and Professional
  light:
    primary: "#ffffff"
    secondary: "#f8fafc"
    accent: "#3b82f6"
    accent_secondary: "#8b5cf6"
    text: "#1e293b"
    text_secondary: "#64748b"
    text_muted: "#94a3b8"
    border: "#e2e8f0"
    border_light: "#f1f5f9"
    background: "#ffffff"
    surface: "#f8fafc"
    surface_hover: "#f1f5f9"
    success: "#10b981"
    warning: "#f59e0b"
    error: "#ef4444"
    info: "#3b82f6"
    
    # Gradients
    gradient_primary: "linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)"
    gradient_secondary: "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%)"
    gradient_surface: "linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)"
    
    # Shadows
    shadow_sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)"
    shadow_md: "0 4px 6px -1px rgba(0, 0, 0, 0.1)"
    shadow_lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1)"
    shadow_xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1)"

  # Dark Theme - Easy on the Eyes
  dark:
    primary: "#0f172a"
    secondary: "#1e293b"
    accent: "#3b82f6"
    accent_secondary: "#8b5cf6"
    text: "#f1f5f9"
    text_secondary: "#94a3b8"
    text_muted: "#64748b"
    border: "#334155"
    border_light: "#475569"
    background: "#0f172a"
    surface: "#1e293b"
    surface_hover: "#334155"
    success: "#10b981"
    warning: "#f59e0b"
    error: "#ef4444"
    info: "#3b82f6"
    
    # Gradients
    gradient_primary: "linear-gradient(135deg, #1e293b 0%, #334155 100%)"
    gradient_secondary: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)"
    gradient_surface: "linear-gradient(135deg, #1e293b 0%, #334155 100%)"
    
    # Shadows
    shadow_sm: "0 1px 2px 0 rgba(0, 0, 0, 0.3)"
    shadow_md: "0 4px 6px -1px rgba(0, 0, 0, 0.4)"
    shadow_lg: "0 10px 15px -3px rgba(0, 0, 0, 0.4)"
    shadow_xl: "0 20px 25px -5px rgba(0, 0, 0, 0.4)"

  # Ocean Theme - Calm and Professional
  ocean:
    primary: "#0c4a6e"
    secondary: "#0e7490"
    accent: "#06b6d4"
    accent_secondary: "#0891b2"
    text: "#f0f9ff"
    text_secondary: "#bae6fd"
    text_muted: "#7dd3fc"
    border: "#0e7490"
    border_light: "#0891b2"
    background: "#0c4a6e"
    surface: "#0e7490"
    surface_hover: "#0891b2"
    success: "#10b981"
    warning: "#f59e0b"
    error: "#ef4444"
    info: "#06b6d4"
    
    # Gradients
    gradient_primary: "linear-gradient(135deg, #0c4a6e 0%, #0e7490 100%)"
    gradient_secondary: "linear-gradient(135deg, #0e7490 0%, #0891b2 100%)"
    gradient_surface: "linear-gradient(135deg, #0e7490 0%, #0891b2 100%)"
    
    # Shadows
    shadow_sm: "0 1px 2px 0 rgba(12, 74, 110, 0.3)"
    shadow_md: "0 4px 6px -1px rgba(12, 74, 110, 0.4)"
    shadow_lg: "0 10px 15px -3px rgba(12, 74, 110, 0.4)"
    shadow_xl: "0 20px 25px -5px rgba(12, 74, 110, 0.4)"

  # Forest Theme - Natural and Green
  forest:
    primary: "#064e3b"
    secondary: "#065f46"
    accent: "#10b981"
    accent_secondary: "#059669"
    text: "#ecfdf5"
    text_secondary: "#a7f3d0"
    text_muted: "#6ee7b7"
    border: "#065f46"
    border_light: "#059669"
    background: "#064e3b"
    surface: "#065f46"
    surface_hover: "#059669"
    success: "#10b981"
    warning: "#f59e0b"
    error: "#ef4444"
    info: "#10b981"
    
    # Gradients
    gradient_primary: "linear-gradient(135deg, #064e3b 0%, #065f46 100%)"
    gradient_secondary: "linear-gradient(135deg, #065f46 0%, #059669 100%)"
    gradient_surface: "linear-gradient(135deg, #065f46 0%, #059669 100%)"
    
    # Shadows
    shadow_sm: "0 1px 2px 0 rgba(6, 78, 59, 0.3)"
    shadow_md: "0 4px 6px -1px rgba(6, 78, 59, 0.4)"
    shadow_lg: "0 10px 15px -3px rgba(6, 78, 59, 0.4)"
    shadow_xl: "0 20px 25px -5px rgba(6, 78, 59, 0.4)"

  # Sunset Theme - Warm and Inviting
  sunset:
    primary: "#7c2d12"
    secondary: "#9a3412"
    accent: "#ea580c"
    accent_secondary: "#dc2626"
    text: "#fef2f2"
    text_secondary: "#fecaca"
    text_muted: "#fca5a5"
    border: "#9a3412"
    border_light: "#ea580c"
    background: "#7c2d12"
    surface: "#9a3412"
    surface_hover: "#ea580c"
    success: "#10b981"
    warning: "#f59e0b"
    error: "#ef4444"
    info: "#ea580c"
    
    # Gradients
    gradient_primary: "linear-gradient(135deg, #7c2d12 0%, #9a3412 100%)"
    gradient_secondary: "linear-gradient(135deg, #9a3412 0%, #ea580c 100%)"
    gradient_surface: "linear-gradient(135deg, #9a3412 0%, #ea580c 100%)"
    
    # Shadows
    shadow_sm: "0 1px 2px 0 rgba(124, 45, 18, 0.3)"
    shadow_md: "0 4px 6px -1px rgba(124, 45, 18, 0.4)"
    shadow_lg: "0 10px 15px -3px rgba(124, 45, 18, 0.4)"
    shadow_xl: "0 20px 25px -5px rgba(124, 45, 18, 0.4)"

# Animation Settings
animations:
  duration:
    fast: "0.15s"
    normal: "0.3s"
    slow: "0.5s"
    slower: "0.8s"
  
  easing:
    ease: "ease"
    ease_in: "ease-in"
    ease_out: "ease-out"
    ease_in_out: "ease-in-out"
    bounce: "cubic-bezier(0.68, -0.55, 0.265, 1.55)"
  
  delays:
    none: "0s"
    short: "0.1s"
    medium: "0.2s"
    long: "0.3s"

# Typography Settings
typography:
  font_family:
    primary: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
    mono: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace"
  
  font_sizes:
    xs: "0.75rem"
    sm: "0.875rem"
    base: "1rem"
    lg: "1.125rem"
    xl: "1.25rem"
    "2xl": "1.5rem"
    "3xl": "1.875rem"
    "4xl": "2.25rem"
    "5xl": "3rem"
    "6xl": "3.75rem"
  
  font_weights:
    light: "300"
    normal: "400"
    medium: "500"
    semibold: "600"
    bold: "700"
    extrabold: "800"

# Spacing Settings
spacing:
  xs: "0.25rem"
  sm: "0.5rem"
  md: "1rem"
  lg: "1.5rem"
  xl: "2rem"
  "2xl": "3rem"
  "3xl": "4rem"
  "4xl": "6rem"

# Border Radius Settings
border_radius:
  none: "0"
  sm: "0.125rem"
  md: "0.375rem"
  lg: "0.5rem"
  xl: "0.75rem"
  "2xl": "1rem"
  full: "9999px" 